apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rv78ndtt3-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rv78ndtt3-java-quarkus-gitops